storage: ./storage

auth:
  authtest:
    numGroups: 200

security:
  api:
    # legacy: true
    jwt:

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
    
  '@*/*':
    # scoped packages
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs
    storage: npmjs

  '**':
    access: $authenticated
    publish: $authenticated
    unpublish: $authenticated
    proxy: npmjs    
    storage: npmjs


# log settings
logs:
  - { type: stdout, format: pretty, level: trace }
